monsieurbiz_sylius_rich_editor_admin_modal_submit:
  path: /monsieurbiz_sylius_rich_editor/modal/submit
  methods: [POST]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\ModalController:submitAction

monsieurbiz_sylius_rich_editor_page_create:
  path: /create
  methods: [GET, POST]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\PageController::new

monsieurbiz_sylius_rich_editor_page_edit:
  path: /{id}/edit
  methods: [GET, POST]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\PageController::edit

monsieurbiz_sylius_rich_editor_page_delete:
  path: /{id}
  methods: [delete]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\PageController::delete

monsieurbiz_sylius_rich_editor_page_index:
  path: /
  methods: [GET]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\PageController::index

monsieurbiz_sylius_rich_editor_page_show:
  path: /{id}
  methods: [GET]
  defaults:
    _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\PageController::show