monsieurbiz_sylius_rich_editor_admin_modal_form:
    path: /monsieurbiz_sylius_rich_editor/modal/edit
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusRichEditorPlugin\Controller\ModalController:formAction
    condition: "request.isXmlHttpRequest()"

monsieurbiz_sylius_rich_editor_page_admin:
    resource: admin_page.yaml
    prefix: '/page'