imports:
  - { resource: "services.yaml" }

monsieur_biz_sylius_rich_editor:
  upload_directory: '%kernel.project_dir%/public/media/rich-editor'

twig:
  paths:
    '%kernel.project_dir%/templates': 'app'
